services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/symfony
    ports:
      - "9000:9000"
    environment:
      - SYMFONY_ENV=dev
    networks:
      - stfalcon_network

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 123456
      MYSQL_USER: 123456
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - stfalcon_network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - stfalcon_network

networks:
  stfalcon_network:
    driver: bridge